FROM postgres:latest

# Configurar variables de entorno (se pueden sobrescribir en docker run)
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=contrasenya
ENV POSTGRES_DB=Database

RUN mkdir -p /var/lib/postgresql/data && chown -R postgres:postgres /var/lib/postgresql/data
RUN rm -rf /var/lib/postgresql/data/lost+found

# Exponer el puerto de PostgreSQL
EXPOSE 5432
