FROM python:3.13-alpine

# Directorio de trabajo
WORKDIR /sotacaballorey

Run apk add --no-cache bash
# Copiar requirements.txt
COPY requirements.txt .

# Instalar dependencias o librerías indicadas en
# requirements.txt (Django, servidor...)
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código fuente
COPY ./sotacaballorey .
COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

# Puerto
EXPOSE 8000
CMD ["./entrypoint.sh"]
