# Generated by Django 5.1.6 on 2025-03-08 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triunfo_palo', models.CharField(choices=[('oros', 'Oros'), ('copas', 'Copas'), ('espadas', 'Espadas'), ('bastos', 'Bastos')], max_length=10)),
                ('mazo_restante', models.JSONField(default=list)),
                ('cartas_jugador_1', models.JSONField(default=list)),
                ('cartas_jugador_2', models.JSONField(default=list)),
                ('cartas_jugadas', models.JSONField(default=list)),
                ('puntos_jugador_1', models.IntegerField(default=0)),
                ('puntos_jugador_2', models.IntegerField(default=0)),
                ('estado_partida', models.CharField(choices=[('EN_JUEGO', 'En juego'), ('FINALIZADO', 'Finalizado')], default='EN_JUEGO', max_length=15)),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_ganadas', to='usuarios.usuario')),
                ('jugador_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_jugador1', to='usuarios.usuario')),
                ('jugador_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_jugador2', to='usuarios.usuario')),
                ('turno_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turno_actual', to='usuarios.usuario')),
            ],
        ),
    ]
