# Generated by Django 5.1.6 on 2025-03-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_amigos_alter_usuario_correo_solicitudamistad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='derrotas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mayor_racha_victorias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='racha_victorias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='victorias',
            field=models.IntegerField(default=0),
        ),
    ]
